spring.application.name=activity01

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wzvajkqlmssdfpkdfdol
spring.datasource.password=IrishJean_Supabase30
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=28OVlEW62q7bUTwpsNCV6fUJyBleZWLnoa5XJXEUFHyy2BfeHhlIcsMvBHF3cEKGSqsWVJNTTqfONoZ7CTEp9g==
jwt.expiration=86400000